name: Cleanup github runner caches on closed pull requests
on:
  pull_request:
    types:
      - closed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  cleanup:
    name: Cleanup PR caches
    runs-on: ubuntu-slim
    permissions:
      actions: write # Needed to run gh cache delete
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
        run: |-
          for key in $(gh cache list --ref "${BRANCH}" --limit 100 --json id --jq '.[].id'); do
              gh cache delete "${key}"
          done
