name: Markdown
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-markdown-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Check
    runs-on: ubuntu-26.04 # to be able to install mdformat
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install mdformat
        run: |
          sudo apt-get update
          sudo apt-get install -y mdformat
      - name: Lint markdown
        run: |-
          mdformat --check .
